AllCops:
  Exclude:
    - 'spec/support/*'
    - 'bin/**/*'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
   - 'spec/**/*'
Metrics/LineLength:
  Exclude:
   - 'spec/**/*'
Lint/UnifiedInteger:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": ()
    "%w": ()
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Security/MarshalLoad:
  Exclude:
    - 'lib/candy_check/play_store/discovery_repository.rb'
